version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpassword
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certs:/etc/letsencrypt
      - certbot-challenges:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
    networks:
      - app-network

  certbot:
    build:
      context: ./certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certbot-challenges:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    networks:
      - app-network

volumes:
  certs:
  certbot-challenges:

networks:
  app-network:
    driver: bridge
